---
namespace: 'r_pufky'
name: 'deb'
version: '4.0.1'
readme: 'README.md'
authors:
  - 'Robert Pufky <rpufky@gmail.com> (https://github.com/r-pufky)'
description: >
  Provides common Debian OS configuration and convenience wrappers for base OS
  configuration and preparation.
license_file: 'LICENSE'
tags:
  - 'debian'
  - 'linux'
  - 'os'
  - 'infrastructure'
  - 'base'
  - 'service'
  - 'tools'
  - 'networking'
dependencies:
  'r_pufky.data': '>=3.2.1,<4.0.0'
  'ansible.posix': '>=2.1.0,<3.0.0'
  'community.general': '>=12.5.0,<13.0.0'
  'community.crypto': '>=3.1.1,<4.0.0'

repository: 'https://github.com/r-pufky/ansible_collection_deb'
documentation: 'https://r-pufky.github.io/ansible_docs'
homepage: 'https://github.com/r-pufky/ansible_collection_deb'
issues: 'https://github.com/r-pufky/ansible_collection_deb/issues'

# Do not include: testing, environments, caches, IDE settings, or staging
# messages in release tarball.
build_ignore:
  - '*.ansible'
  - '*.gitignore'
  - '*.gitattributes'
  - '*.gitmodules'
  - '*.git'
  - '*.venv'
  - '*.envrc'
  - '*.vscode'
  - '*molecule'
  - 'ansible.env'
  - 'pyproject.toml'
  - 'uv.lock'
  - 'TODO.md'
  - 'COMMIT.md'
