---
namespace: 'r_pufky'
name: 'deb'
version: '13.0.4'
readme: 'README.md'
authors:
  - 'Robert Pufky <rpufky@gmail.com> (https://github.com/r-pufky)'
description: |
  Provides common Debian OS configuration and convenience wrappers for base OS
  configuration and preparation.
license_file: 'LICENSE'
tags:
  - 'debian'
  - 'linux'
  - 'os'
  - 'infrastructure'
  - 'base'
  - 'service'
  - 'tools'
  - 'networking'
dependencies:
  'r_pufky.lib': '>=13.0.3,<14.0.0'
  'r_pufky.data': '>=3.0.2'
  'ansible.posix': '=1.6.2'
  'community.general': '=10.6.0'
  'community.crypto': '=2.26.0'
  'moreati.uv': '>=0.0.3'

repository: 'https://github.com/r-pufky/ansible_collection_deb'
documentation:
  'https://github.com/r-pufky/ansible_colection_deb/docs/README.md'
homepage: 'https://github.com/r-pufky/ansible_collection_deb'
issues: 'https://github.com/r-pufky/ansible_collection_deb/issues'

build_ignore:
  - '*molecule/*'  # Do not include molecule testing in release.
  - 'ansible.env'  # Development ansible environment.
  - '.ansible'  # Ansible collection cache for role testing.
  - '.vscode'  # VSCodium settings.
  - 'TODO.md'  # Development staging todo messages.
  - 'COMMIT.md'  # Development staging commit messages.
  - 'docs/*'  # Development docs are a separate repo and not end user.
